############################
# MAIN FOLLOWERS ROUTES
############################

### Get followers for test_user1
GET http://localhost:3000/api/followers/test_user1
Accept: application/json

### Get followers for test_user2
GET http://localhost:3000/api/followers/test_user2
Accept: application/json

### Get followers for test_user3
GET http://localhost:3000/api/followers/test_user3
Accept: application/json



############################
# FOLLOW / UNFOLLOW
############################

### Follow: test_user1 -> test_user2
POST http://localhost:3000/api/followers/follow
Content-Type: application/json
Accept: application/json

{
  "userId": "test_user1",
  "targetUserId": "test_user2"
}

### Unfollow: test_user1 -> test_user2

DELETE http://localhost:3000/api/followers/unfollow
Content-Type: application/json
Accept: application/json

{
  "username": "test_user1",
  "targetUsername": "test_user2"
}


### Test followers logic for test_user1
GET http://localhost:3000/api/followers/test_user1/test
Accept: application/json


# FOLLOW TEST ENDPOINTS


### Run full follow integration test
GET http://localhost:3000/api/followers/follow/test
Accept: application/json


# UNFOLLOW TEST ENDPOINTS 

### Run full unfollow integration test
GET http://localhost:3000/api/followers/unfollow/test
Accept: application/json



##Lindsey Test Routes:: 
### GET all users and who they are following
### GET all users along with the list of users they are following
GET http://localhost:3000/api/following
Accept: application/json

### GET all users that a specific user is following
# Replace USER_ID with a real UUID from your database
GET http://localhost:3000//api/following/11111111-1111-1111-1111-111111111111
Accept: application/json

### Replace USER_ID with a real UUID from your database
GET http://localhost:3000//api/followers/22222222-2222-2222-2222-222222222222
Accept: application/json

### Verify following route via test endpoint
GET http://localhost:3000/api/following/test
Accept: application/json
