### Create a new formula
POST http://localhost:3000/backend/api/formulas/createFormula
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUzOTZhYmZkLWVhYWItNDFlZC1hMTM5LTJmZGMyMGVmZGY2NyIsImVtYWlsIjoiYWxpY2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NzM4ODI3OTUsImV4cCI6MTc3Mzg4NjM5NX0.aR9tRa6NfqJd9HpuJqNmadJ8pCt3eMJwa3qCiKJMpv8
Content-Type: application/json

{
  "name": "Torch Formula",
  "userId": "e396abfd-eaab-41ed-a139-2fdc20efdf67",
  "data": {
    "inputs": [
      { "item": "coal", "quantity": 1 },
      { "item": "stick", "quantity": 1 }
    ],
    "outputs": [
      { "item": "torch", "quantity": 1 }
    ]
  },
  "folderId": null,
  "description": "Base crafting formula for torch"
}

### Get Formula
GET http://localhost:3000/backend/api/formulas/getFormula/da8b48fc-9765-4dbc-8bd3-c71784653a8a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUzOTZhYmZkLWVhYWItNDFlZC1hMTM5LTJmZGMyMGVmZGY2NyIsImVtYWlsIjoiYWxpY2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NzM5NTc5MjYsImV4cCI6MTc3Mzk2MTUyNn0.3BLTPCKpcICq-gHp2XjgfrMEU2SUfZ8WwAJxYn872q8
Content-Type: application/json

### Update formula variables
PUT http://localhost:3000/backend/api/formulas/updateFormula/da8b48fc-9765-4dbc-8bd3-c71784653a8a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUzOTZhYmZkLWVhYWItNDFlZC1hMTM5LTJmZGMyMGVmZGY2NyIsImVtYWlsIjoiYWxpY2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NzM5NTc5MjYsImV4cCI6MTc3Mzk2MTUyNn0.3BLTPCKpcICq-gHp2XjgfrMEU2SUfZ8WwAJxYn872q8
Content-Type: application/json

{
  "name": "Torch Formula Updated",
  "description": "Updated description for torch formula pt 3",
  "folder_id": null,
  "data": {
    "inputs": [
      { "item": "coal", "quantity": 2 },
      { "item": "stick", "quantity": 1 }
    ],
    "outputs": [
      { "item": "torch", "quantity": 1 }
    ]
  },
  "variables": [
    {
      "id": "a1111111-1111-1111-1111-111111111111",
      "name": "Coal",
      "type": "input"
    },
    {
      "id": "b2222222-2222-2222-2222-222222222222",
      "name": "Torch",
      "type": "output"
    },
    {
      "name": "Stick",
      "type": "input"
    }
  ]
}