### Create user: alice
POST http://localhost:3000/backend/api/user/create
Content-Type: application/json

{
  "username": "alice",
  "email": "alice@example.com",
  "password": "123"
}

### Create user: bob
POST http://localhost:3000/backend/api/user/create
Content-Type: application/json

{
  "username": "bob",
  "email": "bob@example.com",
  "password": "123"
}

### Create user: charlie
POST http://localhost:3000/backend/api/user/create
Content-Type: application/json

{
  "username": "charlie",
  "email": "charlie@example.com",
  "password": "123"
}

### Get all users
GET http://localhost:3000/backend/api/user/getAll
Accept: application/json

### Get user by ID
# Replace USER_ID with actual UUID
GET http://localhost:3000/backend/api/user/getUserById/adc8a007-1551-48ac-9504-9cc0ae8ecd7d
Accept: application/json

### Get user by username
GET http://localhost:3000/backend/api/user/getUserByUsername/alice
Accept: application/json

## Edit user
PUT http://localhost:3000/backend/api/user/editUser/adc8a007-1551-48ac-9504-9cc0ae8ecd7d
Authorization: Bearer FAKE_REFRESH_TOKEN
Content-Type: application/json

{
  "username": "alice_updated",
  "email": "alice_new@example.com",
  "password": "newpassword123",
  "biography": "Updated biography"
}

### Delete user
DELETE http://localhost:3000/backend/api/user/deleteById/cb936ebf-d204-4d62-afa7-156dbcb3f4d6

### Get profile image
GET http://localhost:3000/backend/api/user/getProfileImage/USER_ID
Accept: application/json

### Get profile image proxy
GET http://localhost:3000/backend/api/user/getProfileImageProxy/USER_ID
Accept: application/json

### Refresh token
POST http://localhost:3000/backend/api/user/refresh-token
Content-Type: application/json
Accept: application/json

{
  "refreshToken": "FAKE_REFRESH_TOKEN"
}

### Search users
GET http://localhost:3000/backend/api/user/search?query=ali
Accept: application/json

### User likes
GET http://localhost:3000/backend/api/user/userLikes/adc8a007-1551-48ac-9504-9cc0ae8ecd7d
Accept: application/json

### User number of likes
GET http://localhost:3000/backend/api/user/userNumberLikes/adc8a007-1551-48ac-9504-9cc0ae8ecd7d
Accept: application/json

### User total likes
GET http://localhost:3000/backend/api/user/userTotalLikes/adc8a007-1551-48ac-9504-9cc0ae8ecd7d
Accept: application/json