### Get all users
GET http://localhost:3000/backend/api/user/getAll
Accept: application/json

### Get user by ID
# Replace USER_ID with actual UUID
GET http://localhost:3000/backend/api/user/getUserById/efb54cab-52d4-4cc1-9a00-ed2ef8edeed2
Accept: application/json

### Get user by username
GET http://localhost:3000/backend/api/user/getUserByUsername/bob
Accept: application/json

### Edit user
PUT http://localhost:3000/backend/api/user/editUser/6b58a459-40b7-46b7-9dbd-45c036795afd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiNThhNDU5LTQwYjctNDZiNy05ZGJkLTQ1YzAzNjc5NWFmZCIsImVtYWlsIjoiYWxpY2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NzM3NjQ2MjIsImV4cCI6MTc3Mzc2ODIyMn0.UTqFRg-P20p9akme0d2-dJuftUCYTAQBBx4uWg9eDWM
Content-Type: application/json

{
  "username": "alice_updated",
  "email": "alice_new@example.com",
  "password": "newpassword123",
  "biography": "Updated biography"
}

### Delete user
DELETE http://localhost:3000/backend/api/user/deleteById/6b58a459-40b7-46b7-9dbd-45c036795afd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiNThhNDU5LTQwYjctNDZiNy05ZGJkLTQ1YzAzNjc5NWFmZCIsImVtYWlsIjoiYWxpY2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NzM3NjQ2MjIsImV4cCI6MTc3Mzc2ODIyMn0.UTqFRg-P20p9akme0d2-dJuftUCYTAQBBx4uWg9eDWM

### Get profile image
GET http://localhost:3000/backend/api/user/getProfileImage/cb936ebf-d204-4d62-afa7-156dbcb3f4d6
Accept: application/json

### Get profile image proxy
GET http://localhost:3000/backend/api/user/getProfileImageProxy/cb936ebf-d204-4d62-afa7-156dbcb3f4d6
Accept: application/json

### Refresh token
POST http://localhost:3000/backend/api/user/refresh-token
Content-Type: application/json
Accept: application/json

{
  "refreshToken": "FAKE_REFRESH_TOKEN"
}

### Search users
GET http://localhost:3000/backend/api/user/search?query=ali
Accept: application/json

### User likes
GET http://localhost:3000/backend/api/user/userLikes/adc8a007-1551-48ac-9504-9cc0ae8ecd7d
Accept: application/json

### User number of likes
GET http://localhost:3000/backend/api/user/userNumberLikes/adc8a007-1551-48ac-9504-9cc0ae8ecd7d
Accept: application/json

### User total likes
GET http://localhost:3000/backend/api/user/userTotalLikes/adc8a007-1551-48ac-9504-9cc0ae8ecd7d
Accept: application/json