### Create or get chatroom by participants
POST http://localhost:3000/api/chatRoom
Content-Type: application/json
Accept: application/json

{
  "participants": [
    { "userId": "11111111-1111-1111-1111-111111111111" },
    { "userId": "22222222-2222-2222-2222-222222222222" }
  ]
}

### Create a new chatroom for test_user1 and test_user3
POST http://localhost:3000/api/chatRoom
Content-Type: application/json
Accept: application/json

{
  "participants": [
    { "userId": "11111111-1111-1111-1111-111111111111" },
    { "userId": "33333333-3333-3333-3333-333333333333" }
  ]
}

### Create a new chatroom for user2 and user3
POST http://localhost:3000/api/chatRoom
Content-Type: application/json
Accept: application/json

{
  "participants": [
    { "userId": "22222222-2222-2222-2222-222222222222" },
    { "userId": "33333333-3333-3333-3333-333333333333" }
  ]
}

### Get chatrooms by userId (path param)
GET http://localhost:3000/api/chatRoom/getByUserId/11111111-1111-1111-1111-111111111111
Accept: application/json

# ### Verify chatroom route via test endpoint
# GET http://localhost:3000/api/chatroom/test
# Accept: application/json


