### Upload image to a post
POST https://ssu-social-newwave.vercel.app/api/images/create
Content-Type: multipart/form-data; boundary=FormBoundary

--FormBoundary
Content-Disposition: form-data; name="post_id"

33333333-3333-3333-3333-333333333333
--FormBoundary
Content-Disposition: form-data; name="image"; filename="test_image.jpg"
Content-Type: image/jpeg

< ./test_image.jpg
--FormBoundary--


### Delete image by key
DELETE https://ssu-social-newwave.vercel.app/api/images/33333333-3333-3333-3333-333333333333-1761751656384.jpg
